### ISSUE TITLE
Syntax highlighting in Github breaks after ``` without close in documentation comment

### ISSUE THREAD

**Issue by parlough** [dart-lang/dart-syntax-highlight#11]
This may be an issue with linguist, but I haven't had a chance to further investigate yet.

You can see an example in the markdown repository here: https://github.com/dart-lang/markdown/blob/cc57a08156356d7fc8c06c73de972c58ddb39a87/lib/src/block_parser.dart#L421

![image](https://user-images.githubusercontent.com/18372958/82974981-d9730900-9fa0-11ea-8cea-e99f14ff17fa.png)

**Comment by slightfoot** [comment]
Just experienced this issue today with:
https://github.com/arquivolta/desktop/blob/main/lib/platform/win32/arch_to_rootfs.dart

![image](https://github.com/dart-lang/dart-syntax-highlight/assets/906564/4c2ead70-6be0-4844-ae93-d1e6d38092a1)

**Comment by DanTup** [comment]
Odd - I just tested this in VS Code, and although the comment is highlighting incorrectly, the "code" formatting does end at the end of the comment, so the subsequent code is highlighted correctly:

![image](https://github.com/dart-lang/dart-syntax-highlight/assets/1078012/38c96965-8d2d-4b42-bac6-b6eac841b5c7)

So there may be some difference between VS Code and GitHub/Linguist. I'm not sure which is the correct behaviour.

**Comment by DanTup** [comment]
I had a quick look at this, and while VS Code is doing what I _want_, I'm not convinced it's _correct_. My interpretation of the textmate grammar spec seems to suggest what GitHub is doing is correct. I've filed https://github.com/microsoft/vscode/issues/189940 about this to see if VS Code can provide a reason for why it's correct (in which case I'll file with Linguist). If not, and it's deemed a bug in VS Code we can try to find a way to handle this better (which might be to only support triple-backticks in dartdocs at the start of a line, and consider another line with the same _or_ a line that doesn't start with a comment the end).

**Comment by DanTup** [comment]
The conclusion in the issues above was that VS Code is wrong, and therefore this grammar is also wrong (which is a shame, because it will become more complex now we can't rely on `while` to close nested patterns).

I'm working on a change to use `end` and never use `while`, however I [hit an issue](https://github.com/dart-lang/string_scanner/issues/80) in the string scanner we use for tests here while testing it. I've opened [a PR](https://github.com/dart-lang/string_scanner/pull/81) to try and get a fix there (though there are some open questions). I'll come back to this once a fix has landed.

**Comment by DanTup** [comment]
I expect this to be fixed by 5b362281ed55724bb2ed95a03a3d65c2a7c03349 and e1ac5c446c2531343393adbe8fff9d45d8a7c412, but I don't know on what schedule GitHub updates the grammars.

**Comment by DanTup** [comment]
Seems like this has been updated on GitHub, because the code linked and shown in the screenshot above now looks like this (the code at the bottom is no longer coloured like the comment).

![image](https://github.com/user-attachments/assets/89ef3ffb-6590-4170-9130-ade2955dd704)
