### ISSUE TITLE
Syntax highlighting of comments inside of a factory constructor.

### ISSUE THREAD

**Issue by jwren** [dart-lang/dart-syntax-highlight#45]
Syntax of commented out generics, inside of an factory constructor, see line 250:

![Screenshot 2023-05-03 at 11 40 26 AM](https://user-images.githubusercontent.com/1533520/236013259-20f63ec0-558e-49a2-ad7b-3d53fa2cf480.png)

**Comment by jwren** [comment]
@DanTup

**Comment by DanTup** [comment]
Opened a PR at https://github.com/dart-lang/dart-syntax-highlight/pull/46
