### ISSUE TITLE
Add documentation telling folks who update this to update github/linguist

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-syntax-highlight#6]
Should follow-along to update the submodule as changed in https://github.com/github/linguist/commit/96ca71ab99c2f9928d5d69f4c08fd2a51440d045

CC @mit-mit

**Comment by kevmoo** [comment]
I guess we should update https://github.com/dart-lang/dart-syntax-highlight/blob/master/grammars/README.md ? CC @devoncarew

**Comment by devoncarew** [comment]
I don't think the linguist submodule reference to here is pegged to a specific commit? They should just get the updated bits periodically?

**Comment by kevmoo** [comment]
> I don't think the linguist submodule reference to here is pegged to a specific commit? They should just get the updated bits periodically?

It seems these are updated manually 🤷‍♂ 
https://github.com/github/linguist/commits/master/vendor/grammars

**Comment by kevmoo** [comment]
...git submodules are always landed at a specific commit.

**Comment by devoncarew** [comment]
> ...git submodules are always landed at a specific commit.

Ah, gotcha. Then updating the instructions for rolling out changes to the downstream users makes sense.

**Comment by mit-mit** [comment]
I don't think this is needed; my understanding is that the GitHub maintainers update all submodules prior to releasing:

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#releasing

**Comment by kevmoo** [comment]
Oh! Okay. I guess as long as master stays clean

**Comment by devoncarew** [comment]
I don't think we have any action items here -
